context:
  version: "0.4.0"

package:
  name: habitat
  version: ${{ version }}

source:
  url: https://github.com/earendil-works/absurd/archive/refs/tags/${{ version }}.tar.gz
  sha256: 98cdf6c7aa56e23e1ab9db96b674d8d2abd4ea0d34b574fcce19d5e82ecb0b67
  target_directory: src

build:
  number: 0
  # The UI build fails on Windows
  skip: win
  script:
    - cd src/habitat/ui
    - pnpm install
    - pnpm build
    - pnpm-licenses generate-disclaimer --prod --output-file=../../../third-party-licenses.txt
    - cd ../cmd/habitat
    - go-licenses save . --save_path ../../../../library_licenses --ignore habitat
    - go build -v -o $PREFIX/bin/habitat -ldflags="-s -w" .

requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - go-licenses
    - nodejs >=22
    - pnpm
    - pnpm-licenses

tests:
  - script:
      - habitat --help || true
  - package_contents:
      bin:
        - habitat
      strict: true

about:
  homepage: https://github.com/earendil-works/absurd/tree/main/habitat
  summary: Dashboard and monitoring tool for Absurd durable execution system
  description: |
    Habitat is a simple dashboard and monitoring tool for Absurd,
    providing a web UI to visualize and monitor the state of running
    and executed tasks, queues, and events in an Absurd durable execution system.
  license: Apache-2.0
  license_file:
    - src/LICENSE
    - library_licenses/
    - third-party-licenses.txt
  documentation: https://github.com/earendil-works/absurd/tree/main/habitat
  repository: https://github.com/earendil-works/absurd

extra:
  recipe-maintainers:
    - xhochy
